name: Deploy
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: '7.x'
          
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sand4rt'
          
      - run: pnpm publish --filter @sand4rt/experimental-ct-qwik --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
